name: Reportar un error
description: ¿Encontraste un error? Repórtalo aquí
title: "[Error] "
labels: ["error"]
body:
  - type: markdown
    attributes:
     value: |
      Muchas gracias de antemano por tu ayuda. No obstante, necesitamos una serie de informaciones para poder ayudarte.
  - type: checkboxes
    attributes:
      label: "Lista de verificaciones a realizar antes de confirmar la apertura del reporte de error"
      description: Asegúrate de haber completado lo siguiente, de lo contrario, tu reporte puede ser rechazado
      options:
        - label: He logrado reproducir el error en el cliente de SpreenStudio
          required: true
        - label: Puedo reproducir el error en la última versión del cliente de SpreenStudio
          required: true
  - type: dropdown
    attributes:
      label: Sistema operativo
      options:
        - Windows
        - macOS
        - Linux (Basado en Debian/Ubuntu)
        - Linux (Otros)
    validations:
      required: true
  - type: input
    attributes:
      label: Versión del sistema operativo
      placeholder: "Ejemplo: Windows 11 Profesional 21H2 Build 22000.739"
    validations:
        required: true
  - type: input
    attributes:
      label: Hash del commit en el que se encuentra el error
      placeholder: 84d7881b67ecf6088205eca6723bfb19bf2a5f0d
  - type: textarea
    attributes:
      label: Comportamiento esperado
      description: Una descripción de lo que debería ocurrir
      placeholder: El launcher debería...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamiento actual
      description: Una descripción de lo que ocurre con el error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instrucciones para reproducir el error
      placeholder: |
        1. Abrir el launcher
        2. Ir al menú xyz
        3. Hacer clic en abc
        4. Observar
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notas adicionales
      placeholder: Detalles adicionales sobre el error, cualquier cosa que pueda ser útil
    validations:
      required: false
